<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Url;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function menu_link_attributes_form_menu_link_content_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $attributes = \Drupal::config('menu_link_attributes.config')->get('attributes') ?: [];
  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link ? $menu_link->link->first()->options : [];
  $menu_link_attributes = isset($menu_link_options['attributes']) ? $menu_link_options['attributes'] : [];

  $form['options']['attributes'] = [
    '#type' => 'details',
    '#title' => t('Link attributes'),
    '#weight' => -2,
    '#tree' => TRUE,
  ];

  $form['options']['container_attributes'] = [
    '#type' => 'details',
    '#title' => t('Container attributes'),
    '#description' => t('These attributes are applied to the container element (<code>&lt;li&gt;</code>) of the menu link.'),
    '#weight' => -3,
    '#tree' => TRUE,
    '#access' => FALSE,
  ];

  $config_path = Url::fromRoute('menu_link_attributes.config')->toString();
  $referrer_path = parse_url(\Drupal::request()->headers->get('referer'))['path'];
  $coming_from_config = $config_path == $referrer_path;

  // Open <details> element if coming from config page.
  if ($coming_from_config) {
    $form['options']['attributes']['#open'] = TRUE;
  }

  $destination = \Drupal::destination()->getAsArray();
  $config_path = Url::fromRoute('menu_link_attributes.config', [], ['query' => $destination])->toString();

  if (count($attributes)) {
    $form['options']['attributes']['#description'] = '<small>' . t('Manage available attributes <a href="@config">here</a>.', ['@config' => $config_path]) . '</small>';
  }
  else {
    $form['options']['attributes']['help'] = [
      '#markup' => t('Manage available attributes <a href="@config">here</a>.', ['@config' => $config_path]),
    ];
  }

  $autofocus = FALSE;

  // Iterate all defined attributes and create text field for them.
  foreach ($attributes as $attribute => $info) {
    $attributes_key = 'attributes';
    $possible_container_attribute = strpos($attribute, 'container_') === 0;
    $disabled_container = isset($info['container']) && !$info['container'];
    $possible_container_attribute = $possible_container_attribute && !$disabled_container;
    $container_attribute_enabled = isset($info['container']) && $info['container'];

    if ($possible_container_attribute || $container_attribute_enabled) {
      $attributes_key = 'container_attributes';
      $form['options']['container_attributes']['#access'] = TRUE;

      $attribute = preg_replace('/^container_/', '', $attribute);
    }

    // Provide default label / description for attributes.
    if (empty($info['label'])) {
      $info['label'] = str_replace('-', ' ', Unicode::ucfirst($attribute));
    }

    if (empty($info['description'])) {
      $info['description'] = t('Enter value for <code>@attribute</code> attribute.', ['@attribute' => $attribute]);
    }

    // Determine type based on options field.
    if (empty($info['type'])) {
      $type = !empty($info['options']) ? 'select' : 'textfield';
    }
    else {
      $type = $info['type'];
    }

    $form['options'][$attributes_key][$attribute] = [
      '#type' => $type,
      '#title' => $info['label'],
      '#description' => $info['description'],
      '#default_value' => isset($menu_link_attributes[$attribute]) ? $menu_link_attributes[$attribute] : '',
    ];

    // Fill options if select list.
    if ($type == 'select') {
      $form['options'][$attributes_key][$attribute]['#empty_option'] = t('- Select -');
      $form['options'][$attributes_key][$attribute]['#options'] = $info['options'];
    }

    // Add "autofocus" attribute for first attribute input field
    // if coming from config page.
    if ($coming_from_config && !$autofocus) {
      $form['options'][$attributes_key][$attribute]['#attributes'] = ['autofocus' => 'autofocus'];
      $autofocus = TRUE;
    }
  }

  $form['actions']['submit']['#submit'][] = 'menu_link_attributes_menu_link_content_form_submit';
}

/**
 * Submit function for menu add / edit form.
 */
function menu_link_attributes_menu_link_content_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\menu_link_content\Form\MenuLinkContentForm $form_object */
  $form_object = $form_state->getFormObject();
  $menu_link = $form_object->getEntity();
  $menu_link_options = $menu_link->link->first()->options;

  foreach (['attributes', 'container_attributes'] as $attributes_key) {
    $options = [$attributes_key => $form_state->getValue($attributes_key)];
    $merged_options = array_merge($menu_link_options, $options);
    // Filter empty attributes.
    $menu_link_options[$attributes_key] = array_filter($merged_options[$attributes_key]);
  }

  $menu_link->link->first()->options = array_filter($menu_link_options);
  $menu_link->save();
}

/**
 * Implements template_preprocess_menu().
 */
function menu_link_attributes_preprocess_menu(&$variables) {
  foreach ($variables['items'] as $item) {
    /** @var \Drupal\Core\Menu\MenuLinkDefault $menu_link */
    $menu_link = $item['original_link'];
    $options = $menu_link->getOptions();

    // Apply container attributes on <li> element.
    if ($options && isset($options['container_attributes'])) {
      foreach ($options['container_attributes'] as $attribute => $value) {
        $item['attributes']->setAttribute($attribute, $value);
      }
    }
  }
}
